Remove outdated Camel overrides - the orginal issues are now solved i…
quarkusio/quarkus-platform pull request #271
Opened 2021-07-21 14:55 UTC by ppalaga

…n Camel Quarkus

2021-07-21 14:55 UTC, aloubyansky approved these changes

2021-07-21 16:50 UTC, aloubyansky requested changes
@ppalaga are you pushing a rhproduct profile build outcome?

2021-07-21 19:35 UTC, ppalaga commented
> @ppalaga are you pushing a rhproduct profile build outcome?

Of course not, thanks for noticing! I removed the superfluous commits from this branch.

2021-07-22 14:36 UTC, aloubyansky approved these changes

2021-07-22 14:37 UTC, merged