Re-include QOSDK in version 6.0.1
quarkusio/quarkus-platform pull request #826
Opened 2023-04-26 13:00 UTC by metacosm

Make sure that you have run `./mvnw -Dsync` and included the changes in your pull request (preferably in the same commit, unless it makes sense to do otherwise).

Thanks!

2023-04-26 13:42 UTC, aloubyansky commented
@metacosm will 6.0.1 fail with Quarkus 3.0.2.Final?

2023-04-26 14:58 UTC, aloubyansky requested changes
Let's clarify the version update strategy for the JOSDK

2023-04-26 15:42 UTC, metacosm commented
> @metacosm will 6.0.1 fail with Quarkus 3.0.2.Final?

No, the extension defaults to outputting a warning now, previously the default was to fail the build.

2023-05-15 20:39 UTC, aloubyansky approved these changes

2023-05-15 20:40 UTC, merged